### PR TITLE
Added configuration support to the request macros, commands, and blade directives

### PR DESCRIPTION
**Pull request by neoighodaro**
Sometimes, people do not want to load the macros or some specific command. This allows them to remove a specific command or macro or directive from being registered entirely. This does not break compatibility.

### CODE REVIEW

**Comment by neoighodaro** [comment]
Any chance this will be merged?

**Comment by akalongman** [comment]
@neoighodaro thank you for PR. I need some time for reviewing the changes

**Comment by neoighodaro** [comment]
It's not that big of a change @akalongman is it going to take long? I can create a fork and keep updating if it is

**Comment by akalongman** [comment]
@neoighodaro I will take a look tomorrow

**Comment by akalongman** [comment]
@neoighodaro `LodashServiceProvider` does not load by default, so I don't see any advantage in this config parameters. If you do not want any macros or commands, just do not load service provider.
I think its better to add 3 options like `load_macros`, `load_directives`, `load_commands`. What do you think?

**Pull request closed without merging**
